enum StatusPedidos {
  PAGAMENTO_REALIZADO = 'PAGAMENTO_REALIZADO',
  PAGAMENTO_REJEITADO = 'PAGAMENTO_REJEITADO',
  EM_TRANSPORTE = 'EM_TRANSPORTE',
  ENTREGUE = 'ENTREGUE',
  CANCELADO = 'CANCELADO',
}

export { StatusPedidos };
