enum TrocaDevolucaoStatus {
  TROCA_SOLICITADA,
  TROCA_ACEITA,
  TROCA_RECUSADA,

  DEVOLUCAO_SOLICITADA,
  DEVOLUCAO_ACEITA,
  DEVOLUCAO_RECUSADA,
  DEVOLUCAO_REALIZADA,
}

export { TrocaDevolucaoStatus };
