enum TrocaDevolucaoStatus {
  TROCA_SOLICITADA = 'TROCA_SOLICITADA',
  TROCA_ACEITA = 'TROCA_ACEITA',
  TROCA_RECUSADA = 'TROCA_RECUSADA',
  TROCA_REALIZADA = 'TROCA_REALIZADA',

  DEVOLUCAO_SOLICITADA = 'DEVOLUCAO_SOLICITADA',
  DEVOLUCAO_ACEITA = 'DEVOLUCAO_ACEITA',
  DEVOLUCAO_RECUSADA = 'DEVOLUCAO_RECUSADA',
  DEVOLUCAO_REALIZADA = 'DEVOLUCAO_REALIZADA',
}

export { TrocaDevolucaoStatus };
